### ISSUE TITLE
9/16 Dinner 19:30

### ISSUE THREAD

**Issue by JuanitoFatas** [JuanitoFatas/hiroshima#1]
- Restaurant: http://namonakimise.net
- Tabelog: https://tabelog.com/en/hiroshima/A3401/A340101/34001419/
- Google Map: https://goo.gl/maps/FktG72mp6Dv

**Comment by sunkai612** [comment]
😋👌🏼

**Comment by JuanitoFatas** [comment]
https://twitter.com/JuanitoFatas/status/909077766896705536
